# Generated by Django 6.1.1 on 2026-09-04 09:07

import django.db.models.deletion
import lobbies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=lobbies.models.new_code, max_length=5, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('playing', 'Playing'), ('finished', 'Finished')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'lobbies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('token', models.CharField(db_index=True, default=lobbies.models.new_token, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=16)),
                ('is_host', models.BooleanField(default=False)),
                ('seat', models.IntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lobbies.lobby')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='lobbies.lobby')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='lobbies.member')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=0)),
                ('blob', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='lobbies.lobby')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='lobbies.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('is_host', True)), fields=('lobby',), name='one_host_per_lobby'),
        ),
        migrations.AddIndex(
            model_name='intent',
            index=models.Index(fields=['lobby', 'delivered', 'id'], name='lobbies_int_lobby_i_668557_idx'),
        ),
    ]
