# Generated by Django 6.1.1 on 2026-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0002_lobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
