# Generated by Django 6.1.1 on 2026-09-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_code', models.CharField(blank=True, max_length=8)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('rounds', models.IntegerField(default=0)),
                ('player_count', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=40)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=16)),
                ('won', models.BooleanField(default=False)),
                ('pegs', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('jokers_used', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='stats.gameresult')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='stats.profile')),
            ],
            options={
                'ordering': ['seat'],
                'constraints': [models.UniqueConstraint(fields=('game', 'seat'), name='one_row_per_seat'), models.CheckConstraint(condition=models.Q(('questions_correct__lte', models.F('questions_attempted'))), name='correct_within_attempted')],
            },
        ),
    ]
